### ISSUE TITLE
Removendo todas as culturas de uma única vez.

### ISSUE THREAD

**Issue by eduardoGCordeiro** [luisthiagop/swfaes#10]
Quando remove uma cultura do talhao m45 (criado para testes), tentei remove-lo para testar a deleção de talhões. Após a deleção ocorrer, todas as culturas, independente de talhão, foram deletadas.

**Comment by luisthiagop** [comment]
Testei e não aconteceu isso... Você pode rever no [servidor](http://swfaes.sytes.net/culturas)?

**Comment by eduardoGCordeiro** [comment]
Está com o servidor atualizado com nosso desenvolvimento?

**Comment by luisthiagop** [comment]
![captura de tela de 2018-11-17 11-46-50](https://user-images.githubusercontent.com/5614838/48661767-a15f4180-ea5e-11e8-83ea-493a7bb90937.png)

**Comment by eduardoGCordeiro** [comment]
Estou com o problema localmente, de pull em minha branch e suba pro servidor para verificar se não ocorre mesmo. Subi atualizações sobre a deleção de talhões e exibição.
