### ISSUE TITLE
corrigir listagem dos talhões dos funcionários 

### ISSUE THREAD

**Issue by luisthiagop** [luisthiagop/swfaes#12]
Achei que a gente já tinha arrumado isso.

**Comment by eduardoGCordeiro** [comment]
Em minha branch está funcionando ok

**Comment by luisthiagop** [comment]
para todos os usuários?
![captura de tela de 2018-11-17 11-40-11](https://user-images.githubusercontent.com/5614838/48661718-9e178600-ea5d-11e8-8fd6-aee1a5dc3aa1.png)

**Comment by luisthiagop** [comment]
Acho que atualmente não ta verificando quando o usuário não tem talhões dai tenta exibir, mas não tem nada.

**Comment by luisthiagop** [comment]
Corrigido!
