### ISSUE TITLE
Remover acesso do usuário e conceder novamente, ao acessar o menu talhões erro.

### ISSUE THREAD

**Issue by luisthiagop** [luisthiagop/swfaes#6]
Ver o que acontece com os talhões que o eram administrados apos tirar acesso ao sistema.

**Comment by eduardoGCordeiro** [comment]
Continuam vinculados ao administrador de talhão, o acesso ao sistema não regulamenta a administração do talhão. A administração do talhão só pode ser modificada ao editar um talhão. Esta correto!

**Comment by luisthiagop** [comment]
Ta dando tela de erro quando tento entrar eem talhoes com adm de talhao sem talhão

**Comment by eduardoGCordeiro** [comment]
![captura de tela de 2018-11-15 12-35-28](https://user-images.githubusercontent.com/29361711/48559536-f53d1f80-e8d2-11e8-9ac0-583a72e9ce7f.png)

Está ok, rever a branch.

**Comment by luisthiagop** [comment]
entre com o usuário 10094981930 senha: fazendaescola

**Comment by eduardoGCordeiro** [comment]
Usuário não está inserido na tabela adms_talhoes, inseri e agora está funcionando.

**Comment by eduardoGCordeiro** [comment]
Resolvido?

**Comment by luisthiagop** [comment]
acredito que sim kkkk
