### ISSUE TITLE
Corrigir problema com deleção dos talhões

### ISSUE THREAD

**Issue by luisthiagop** [luisthiagop/swfaes#8]
![captura de tela de 2018-11-15 15-07-55](https://user-images.githubusercontent.com/5614838/48569244-528f9b80-e8e8-11e8-8a18-b3d413661fa8.png)

**Comment by eduardoGCordeiro** [comment]
Bug ocorre ao remover talhões que possuem culturas e requisições, a validação foi acrescentada no Controller na função destroy dos Talhoes.
